#!/usr/bin/env python3
"""Generate compact runtime metadata after verifying explicit collectible identities."""
import argparse
import json
import pathlib

from apply_collectible_crosswalk import load_json, rebuild

ROOT = pathlib.Path(__file__).resolve().parents[1]
PACK = ROOT / "data" / "collectibles"
INPUT = PACK / "collectibles.json"
CROSSWALK = PACK / "crosswalk.json"
CATALOG = PACK / "coordinate_catalog.json"
OUTPUT = ROOT / "source" / "CollectibleInfoData.cpp"
TYPE = {
    "tags": "Tag",
    "snapshots": "Snapshot",
    "horseshoes": "Horseshoe",
    "oysters": "Oyster",
    "stunt_jumps": "StuntJump",
}


def quote(text):
    return json.dumps(text, ensure_ascii=False)


def validate_canonical(data):
    expected = rebuild(data, load_json(CROSSWALK), load_json(CATALOG))
    if data != expected:
        raise SystemExit(
            "canonical collectibles.json disagrees with crosswalk/coordinate_catalog; "
            "run tools/apply_collectible_crosswalk.py"
        )


def render(data):
    items = data["items"]
    lines = [
        "// Generated by tools/generate_collectible_info.py; do not edit manually.",
        '#include "CollectibleInfo.hpp"',
        "",
        "namespace gtasa {",
        "namespace {",
        "const CollectibleInfo kCollectibleInfo[] = {",
    ]
    for item in items:
        world = item["world"]
        lookup = item["lookup"]
        lines.append(
            "    {CollectibleType::%s, %d, %.6ff, %.6ff, %.6ff, %s, %s, %s, %d},"
            % (
                TYPE[item["type"]],
                item["canonical_id"],
                world["x"],
                world["y"],
                world["z"],
                quote(item["description_en"]),
                quote(item["description_ru"]),
                quote(item["image"]),
                lookup.get("save_order_id", 0),
            )
        )
    lines += ["};", "", "const int kTagCanonicalBySaveOrder[100] = {"]
    reverse = [0] * 100
    for item in items:
        if item["type"] == "tags":
            save_id = int(item["lookup"]["save_order_id"])
            if reverse[save_id - 1]:
                raise ValueError(f"duplicate tag save_order_id: {save_id}")
            reverse[save_id - 1] = int(item["canonical_id"])
    if any(value == 0 for value in reverse):
        raise ValueError("incomplete tag save-order reverse lookup")
    lines.extend("    %d," % value for value in reverse)
    lines += [
        "};",
        "} // namespace",
        "",
        "const CollectibleInfo* collectibleInfo(CollectibleType type, int canonicalId) {",
        "    for (const auto& info : kCollectibleInfo)",
        "        if (info.type == type && info.canonicalId == canonicalId) return &info;",
        "    return nullptr;",
        "}",
        "const CollectibleInfo* collectibleInfoForRuntime(const Collectible& collectible) {",
        "    if (collectible.type == CollectibleType::Tag) {",
        "        const int saveOrder = collectible.sourceIndex + 1;",
        "        return saveOrder >= 1 && saveOrder <= 100 ? collectibleInfo(collectible.type, kTagCanonicalBySaveOrder[saveOrder - 1]) : nullptr;",
        "    }",
        "    const CollectibleInfo* closest = nullptr; double best = 0.0; bool ambiguous = false;",
        "    for (const auto& info : kCollectibleInfo) {",
        "        if (info.type != collectible.type) continue;",
        "        const double dx = info.x - collectible.x, dy = info.y - collectible.y, dz = info.z - collectible.z;",
        "        const double distance2 = dx * dx + dy * dy + dz * dz;",
        "        if (!closest || distance2 < best) { closest = &info; best = distance2; ambiguous = false; }",
        "        else if (distance2 == best) ambiguous = true;",
        "    }",
        "    // Save pickup coordinates are quantised; stunt-jump centres can differ from the authored point.",
        "    const double limit = collectible.type == CollectibleType::StuntJump ? 2500.0 : 9.0;",
        "    return !ambiguous && closest && best <= limit ? closest : nullptr;",
        "}",
        "std::size_t collectibleInfoCount() { return sizeof(kCollectibleInfo) / sizeof(kCollectibleInfo[0]); }",
        "} // namespace gtasa",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(INPUT.read_text(encoding="utf-8"))
    if data.get("schema") != "gtasa-unexplored-collectibles-v1" or len(data.get("items", [])) != 320:
        raise SystemExit("unexpected collectibles dataset")
    validate_canonical(data)
    generated = render(data)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("generated CollectibleInfoData.cpp is stale")
        print("generated CollectibleInfoData.cpp is current")
        return
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
