#!/usr/bin/env python3
"""Generate the POI runtime table from the auditable JSON pack."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "data" / "poi" / "poi.json"
OUTPUT = ROOT / "source" / "PoiInfoData.cpp"
VALID = {"cross_checked_xyz", "representative_2d"}
POI_CATEGORIES = {
    "story": "Story",
    "landmark": "Landmark",
    "nature": "Nature",
    "mystery": "Mystery",
    "business": "Business",
}


def q(value):
    return json.dumps(value, ensure_ascii=False)


def render(data):
    lines = ["// Generated by tools/generate_poi_info.py; do not edit manually.",
             '#include "PoiInfo.hpp"', "", "namespace gtasa {", "namespace {",
             "const PoiInfo kPoiInfo[] = {"]
    for item in data["items"]:
        if item.get("category") not in POI_CATEGORIES:
            raise SystemExit("unknown POI category: %s" % item.get("id"))
        visible = item["coordinate_status"] in VALID
        world = item["world"] or {"x": 0.0, "y": 0.0, "z": 0.0}
        z = world["z"] if world["z"] is not None else 0.0
        representative = item["coordinate_status"] == "representative_2d"
        lines.append("    {%d, %.6ff, %.6ff, %.6ff, %s, %s, PoiCategory::%s, %s, %s, %s, %s, %s}," % (
            item["id"], world["x"], world["y"], z, str(visible).lower(), str(representative).lower(),
            POI_CATEGORIES[item["category"]], q(item["name_en"]), q(item["name_ru"]), q(item["description_en"]), q(item["description_ru"]),
            q(item["image"])))
    lines += ["};", "} // namespace", "",
              "const PoiInfo* poiInfo(std::size_t index) {",
              "    return index < sizeof(kPoiInfo) / sizeof(kPoiInfo[0]) ? &kPoiInfo[index] : nullptr;",
              "}", "std::size_t poiInfoCount() { return sizeof(kPoiInfo) / sizeof(kPoiInfo[0]); }",
              "} // namespace gtasa", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(INPUT.read_text(encoding="utf-8"))
    if data.get("schema") != "gtasa-unexplored-poi-pack-v1" or len(data.get("items", [])) != 80:
        raise SystemExit("unexpected POI dataset")
    for item in data["items"]:
        status, world = item["coordinate_status"], item["world"]
        if status in VALID and not world:
            raise SystemExit("visible POI without world point: %s" % item["id"])
        if status == "representative_2d" and world["z"] is not None:
            raise SystemExit("representative POI has a fictional Z: %s" % item["id"])
    generated = render(data)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("generated PoiInfoData.cpp is stale")
    else:
        OUTPUT.write_text(generated, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
